name: TNTStick
version: '${version}'
main: com.demurestpie.tntstick.TNTStick
api-version: '1.20'

commands:
  tntstick:
    description: Gives the player a TNTStick
    usage: /<command>
    permission: tntstick.tntstick
  tntamount:
    description: Changes the amount of TNT that is shot out of the TNTStick
    usage: /<command>
    permission: tntstick.tntamount
  tntsize:
    description: Changes the size of the TNT that is shot out of the TNTStick
    usage: /<command>
    permission: tntstick.tntsize